#!/usr/bin/python

import sys
from urlparse import urlparse

# forward

def dtMktBackpage(*args):
    pass
def dtMktCraigslist(*args):
    pass
def dtMktClassivox(*args):
    pass
def dtMktMyproviderguide(*args):
    pass
def dtMktNaughtyreviews(*args):
    pass
def dtMktRedbook(*args):
    pass
def dtMktCityvibe(*args):
    pass
def dtMktMassagetroll(*args):
    pass
def dtMktRedbook_forum(*args):
    pass
def dtMktCityxguide(*args):
    pass
def dtMktCityxguideforum(*args):
    pass
def dtMktRubads(*args):
    pass
def dtMktAnunico(*args):
    pass
def dtMktSipsap(*args):
    pass
def dtMktEscortsincollege(*args):
    pass
def dtMktEscortphonelist(*args):
    pass
def dtMktEroticmugshots(*args):
    pass
def dtMktEscortadsxxx(*args):
    pass
def dtMktEscortsinca(*args):
    pass
def dtMktEscortsintheus(*args):
    pass
def dtMktLiveescortreviews(*args):
    pass
def dtMktMyproviderguideforum(*args):
    pass
def dtMktUsasexguide(*args):
    pass
def dtMktEroticreview(*args):
    pass
def dtMktAdultsearch(*args):
    pass
def dtMktHappymassage(*args):
    pass
def dtMktUtopiaguide(*args):
    pass
def dtMktMissingkids(*args):
    pass
def dtMktAlibaba(*args):
    pass
def dtMktJustlanded(*args):
    pass
def dtMktGmdu(*args):
    pass
def dtMktTradekey(*args):
    pass
def dtMktManpowervacancy(*args):
    pass
def dtMktGulfjobsbank(*args):
    pass
def dtMktEc21(*args):
    pass

sources_by_id = {
                 1: "backpage",
                 2: "craigslist",
                 3: "classivox",
                 4: "myproviderguide",
                 5: "naughtyreviews",
                 6: "redbook",
                 7: "cityvibe",
                 8: "massagetroll",
                 9: "redbook_forum",
                 10: "cityxguide",
                 11: "cityxguideforum",
                 12: "rubads",
                 13: "anunico",
                 14: "sipsap",
                 15: "escortsincollege",
                 16: "escortphonelist",
                 17: "eroticmugshots",
                 18: "escortadsxxx",
                 19: "escortsinca",
                 20: "escortsintheus",
                 21: "liveescortreviews",
                 22: "myproviderguideforum",
                 23: "usasexguide",
                 24: "eroticreview",
                 25: "adultsearch",
                 26: "happymassage",
                 27: "utopiaguide",
                 28: "missingkids",
                 29: "alibaba",
                 30: "justlanded",
                 31: "gmdu",
                 32: "tradekey",
                 33: "manpowervacancy",
                 34: "gulfjobsbank",
                 35: "ec21"}

def clean(x):
    return str(x).replace(' ', '')

def marketid_to_market_tuple(source_columns, marketid):
    # return "mtmt-1"
    try:
        escape = "mtmt0"
        minfo = market_id_to_market_info.get(marketid, None)
        escape = "mtmt1"
        if not minfo:
            escape = "mtmt2a"
            return escape
            print >> sys.stderr, "Need to define a tuple for FAA/ICAO %s" % marketid
            return "mtmt2a"
            return None
        else:
            escape = "mtmt2b"
            locality = minfo[3]
            adm1 = minfo[2]
            country = minfo[1]
            escape = [source_columns] + [str(x) for x in minfo]
            return escape
    except:
        escape = "mtmt3"
        return escape

def mkSrcMktUri(source_columns, sourcename, sitekey, base='http://dig.isi.edu/'):
    if not isinstance(source_columns, list):
        source_columns=[source_columns]
    return "%s/sourcemarket/%s/%s/%s" % (base, sourcename, '-'.join(source_columns), sitekey)

### BACKPAGE

backpage_sitekey_to_marketid = {
                                "albany": "ALB",
                                "queens": "JFK",
                                "longisland": "ISP"
                                }

def backpage_url_to_sitekey(url):
    """http://longisland.backpage.com/FemaleEscorts/s-mny-oo-chics-but-oo-nn-lik-oo-me-19/40317377"""
    (scheme, netloc, path, params, query, fragment) = urlparse(url)
    sitekey = netloc.split('.')[0]
    return sitekey

def dtMktBackpage(url, title, city, state):
    return marketid_to_market_tuple("url",backpage_sitekey_to_marketid[backpage_url_to_sitekey(url)])
def dtMktBackpage(url, title, city, state):
    return mkSrcMktUri("url","backpage",backpage_url_to_sitekey(url))

## MYPROVIDERGUIDE

myproviderguide_sitekey_to_marketid = {
                                       "abilene": "ABI",
                                       "akron": "CAK",
                                       "albany": "ALB",
                                       "albuquerque": "ABQ",
                                       "allentown": "ABE",
                                       "altoona": "AOO",
                                       "amarillo": "AMA",
                                       "ames-ia": "AMW",
                                       "amsterdam": "AMS",
                                       "ann-arbor": "ARB",
                                       "annapolis": "ANP",
                                       "appleton": "ATW",
                                       "asheville": "AVL",
                                       "athens-ga": "AHN",
                                       "athens-oh": "ATO",
                                       "atlanta": "ATL",
                                       "auburn": "AUO",
                                       "augusta": "AGS",
                                       "austin": "AUS",
                                       "bakersfield": "BFL",
                                       "baltimore": "BWI",
                                       "barrie": "QEB",
                                       "bath": "BRS",
                                       "baton-rouge": "BTR",
                                       "beaumont": "BPT",
                                       "belfast": "BFS",
                                       "belleville": "YTR",
                                       "bellingham": "BLI",
                                       "bend": "RDM",
                                       "berlin": "TXL",
                                       "biloxi": "GPT",
                                       "binghamton": "BGM",
                                       "birmingham": "BHM",
                                       "birmingham-uk": "BHX",
                                       "bismarck": "BIS",
                                       "blacksburg": "BCB",
                                       "bloomington": "BMG",
                                       "bloomington-normal": "BMI",
                                       "boise": "BOI",
                                       "boone": "NC06",
                                       "boston": "BOS",
                                       "boulder": "WBU",
                                       "bowling-green": "BWG",
                                       "brighton": "ESH",
                                       "bristol": "BRS",
                                       "bronx": "JFK",
                                       "brooklyn": "JFK",
                                       "brunswick-ga": "BQK",
                                       "brussels": "BRU",
                                       "budapest": "BUD",
                                       "buffalo": "BUF",
                                       "calgary": "YYC",
                                       "cambridge": "CBG",
                                       "cape-cod": "PVC",
                                       "carbondale": "MDH",
                                       "cardiff": "CWL",
                                       "catskills": "20N",
                                       "cedar-rapids": "CID",
                                       "central-jersey": "47N",
                                       "champaign": "CMI",
                                       "charleston-sc": "CHS",
                                       "charleston-wv": "CRW",
                                       "charlotte": "CLT",
                                       "charlottesville": "CHO",
                                       "chatham": "XCM",
                                       "chattanooga": "CHA",
                                       "chautauqua": "JHW",
                                       "chicago": "ORD",
                                       "chico": "CIC",
                                       "cincinnati": "CVG",
                                       "clarksville": "CKV",
                                       "cleveland": "CLE",
                                       "colorado-springs": "COS",
                                       "columbia-sc": "CAE",
                                       "columbus": "CMH",
                                       "columbus-ga": "CSG",
                                       "copenhagen": "CPH",
                                       "cornwall": "YCC",
                                       "corpus-christi": "CRP",
                                       "corvallis": "CVO",
                                       "coventry": "CVT",
                                       "cranbrook": "YXC",
                                       "dallas": "DFW",
                                       "danville": "DAN",
                                       "dayton": "DAY",
                                       "daytona-beach": "DAB",
                                       "decatur-il": "DEC",
                                       "delaware": "ILG",
                                       "denton": "DFW",
                                       "denver": "DEN",
                                       "derby": "EMA",
                                       "des-moines": "DSM",
                                       "detroit": "DTW",
                                       "devon": "EXT",
                                       "dothan-al": "DHN",
                                       "dublin": "DUB",
                                       "dubuque": "DBQ",
                                       "duluth": "DLH",
                                       "dundee": "DND",
                                       "eau-claire": "EAU",
                                       "edinburgh": "EDI",
                                       "edmonton": "YEG",
                                       "elmira-corning": "ELM",
                                       "erie-pa": "ERI",
                                       "essex": "STN",
                                       "eugene": "EUG",
                                       "evansville": "EVV",
                                       "fargo": "FAR",
                                       "farmington-nm": "FMN",
                                       "fayetteville": "FAY",
                                       "fayetteville-ar": "XNA",
                                       "flagstaff": "FLG",
                                       "flint": "FNT",
                                       "florence": "FLO",
                                       "florence-sc": "FLO",
                                       "florida-keys": "EYW",
                                       "fort-collins": "FNL",
                                       "fort-lauderdale": "FLL",
                                       "fort-myers": "RSW",
                                       "fort-smith-ar": "FSM",
                                       "fort-wayne": "FWA",
                                       "fort-worth": "DFW",
                                       "fredericksburg": "EZF",
                                       "fresno": "FAT",
                                       "gadsden-anniston": "GAD",
                                       "gainesville": "GNV",
                                       "galveston": "GLS",
                                       "glasgow": "GLA",
                                       "gold-country": "O22",
                                       "grand-island": "GRI",
                                       "grand-rapids": "GRR",
                                       "green-bay": "GRB",
                                       "greensboro": "GSO",
                                       "greenville": "GSP",
                                       "guelph": "CNC4",
                                       "halifax": "YHZ",
                                       "hamilton": "YHM",
                                       "hampshire": "SOU",
                                       "hampton": "ORF",
                                       "harrisburg": "MDT",
                                       "harrisonburg": "SHD",
                                       "hartford": "HFD",
                                       "hattiesburg": "HBG",
                                       "hickory": "HKY",
                                       "hilton-head": "HHH",
                                       "honolulu": "HNL",
                                       "houston": "IAH",
                                       "hudson-valley": "SWF",
                                       "humboldt-county": "ACV",
                                       "huntington-ashland": "HTS",
                                       "huntsville": "HSV",
                                       "imperial-county": "IPL",
                                       "indianapolis": "IND",
                                       "inland-empire": "ONT",
                                       "iowa-city": "IOW",
                                       "ithaca": "ITH",
                                       "jackson-mi": "JXN",
                                       "jackson-ms": "JAN",
                                       "jackson-tn": "MKL",
                                       "jacksonville": "JAX",
                                       "janesville": "JVL",
                                       "jersey-shore": "ACY",
                                       "jonesboro": "JBR",
                                       "joplin": "JLN",
                                       "kalamazoo": "AZO",
                                       "kamloops": "YKA",
                                       "kansas-city": "MCI",
                                       "kelowna": "YLW",
                                       "kennewick-pasco-richland": "PSC",
                                       "kenosha-racine": "RAC",
                                       "kent": "LYX",
                                       "killeen": "GRK",
                                       "kingston": "YGK",
                                       "kitchener": "YKF",
                                       "knoxville": "TYS",
                                       "la-crosse": "LSE",
                                       "lafayette": "LFT",
                                       "lake-charles": "LCH",
                                       "lakeland": "LAL",
                                       "lancaster-pa": "LNS",
                                       "lansing": "LAN",
                                       "laredo": "LRD",
                                       "las-vegas": "LAS",
                                       "lawrence": "LWC",
                                       "lawton": "LAW",
                                       "leeds": "LBA",
                                       "lehigh-valley": "ABE",
                                       "lethbridge": "YQL",
                                       "lexington-ky": "LEX",
                                       "lima": "AOH",
                                       "lincoln": "LNK",
                                       "little-rock": "LIT",
                                       "liverpool": "LPL",
                                       "logan": "LGU",
                                       "london": "LHR",
                                       "london-canada": "YXU",
                                       "long-island": "ISP",
                                       "los-angeles": "LAX",
                                       "louisville": "SDF",
                                       "lubbock": "LBB",
                                       "lynchburg": "LYH",
                                       "macon": "MCN",
                                       "madison": "MSN",
                                       "maine": "PWM",
                                       "manchester": "MAN",
                                       "manhattan-ks": "MHK",
                                       "mankato": "MKT",
                                       "mansfield": "MFD",
                                       "martinsburg": "MRB",
                                       "medford-ashland-klamath": "MFR",
                                       "memphis": "MEM",
                                       "mendocino-county": "UKI",
                                       "merced": "MCE",
                                       "miami": "MIA",
                                       "milwaukee": "MKE",
                                       "minneapolis": "MSP",
                                       "minot": "MOT",
                                       "mobile": "MOB",
                                       "modesto": "MOD",
                                       "mohave-county": "IFP",
                                       "monroe-la": "MLU",
                                       "montana": "HLN",
                                       "monterey-bay": "MRY",
                                       "montgomery": "MGM",
                                       "montreal": "YUL",
                                       "morgantown": "MGW",
                                       "mumbai": "BOM",
                                       "muncie": "MIE",
                                       "munich": "MUC",
                                       "muskegon": "MKG",
                                       "myrtle-beach": "MYR",
                                       "nanaimo": "YCD",
                                       "nashville": "BNA",
                                       "new-brunswick": "YQM",
                                       "new-delhi": "DEL",
                                       "new-hampshire": "MHT",
                                       "new-haven": "HVN",
                                       "new-orleans": "MSY",
                                       "new-york": "JFK",
                                       "newcastle": "NCL",
                                       "newfoundland": "YYT",
                                       "niagara": "YCM",
                                       "norfolk": "ORF",
                                       "north-dakota": "FAR",
                                       "north-jersey": "EWR",
                                       "norwich": "NWI",
                                       "nottingham": "NQT",
                                       "oakland": "OAK",
                                       "ocala": "OCF",
                                       "odessa": "MAF",
                                       "ogden-clearfield": "OGD",
                                       "oklahoma-city": "OKC",
                                       "omaha": "OMA",
                                       "orange-county": "SNA",
                                       "orlando": "MCO",
                                       "oslo": "OSL",
                                       "ottawa": "YOW",
                                       "outer-banks": "FFA",
                                       "owen-sound": "YOS",
                                       "oxford": "OXF",
                                       "palm-springs-ca": "PSP",
                                       "panama-city-fl": "PFN",
                                       "paris": "CDG",
                                       "parkersburg-marietta": "PKB",
                                       "pensacola": "PNS",
                                       "peoria": "PIA",
                                       "peterborough": "YPQ",
                                       "philadelphia": "PHL",
                                       "phoenix": "PHX",
                                       "pittsburgh": "PIT",
                                       "plattsburgh-adirondacks": "PBG",
                                       "poconos": "MPO",
                                       "port-huron": "PHN",
                                       "portland": "PDX",
                                       "prescott": "PRC",
                                       "prince-george": "YXS",
                                       "providence": "PVD",
                                       "provo": "PVU",
                                       "pueblo": "PUB",
                                       "pullman": "PUW",
                                       "quebec": "YQB",
                                       "queens": "JFK",
                                       "raleigh": "RDU",
                                       "reading": "RDG",
                                       "red-deer": "YQF",
                                       "redding": "RDD",
                                       "regina": "YQR",
                                       "reno": "RNO",
                                       "richmond": "RIC",
                                       "roanoke": "ROA",
                                       "rochester-mn": "RST",
                                       "rochester-ny": "ROC",
                                       "rockford": "RFD",
                                       "rocky-mountains": "EGE",
                                       "roseburg": "RBG",
                                       "roswell": "ROW",
                                       "sacramento": "SMF",
                                       "saginaw-midland-baycity": "MBS",
                                       "saguenay": "YBG",
                                       "saint-louis": "STL",
                                       "salem-or": "SLE",
                                       "salt-lake-city": "SLC",
                                       "san-antonio": "SAT",
                                       "san-diego": "SAN",
                                       "san-fernando-valley": "BUR",
                                       "san-francisco": "SFO",
                                       "san-jose": "SJC",
                                       "san-luis-obispo": "SBP",
                                       "san-marcos": "HYI",
                                       "sandusky": "SKY",
                                       "santa-barbara": "SBA",
                                       "santa-fe": "SAF",
                                       "sarasota-bradenton": "SRQ",
                                       "sarnia": "YZR",
                                       "saskatchewan": "YXE",
                                       "savannah": "SAV",
                                       "scranton": "AVP",
                                       "seattle": "SEA",
                                       "sheboygan-wi": "SBM",
                                       "sheffield": "DSA",
                                       "sherbrooke": "YSC",
                                       "shreveport": "SHV",
                                       "sierra-vista": "FHU",
                                       "sioux-city-ia": "SUX",
                                       "skagit": "BVS",
                                       "south-bend": "SBN",
                                       "south-dakota": "PIR",
                                       "south-jersey": "MIV",
                                       "space-coast": "TIX",
                                       "spokane": "GEG",
                                       "springfield-il": "SPI",
                                       "springfield-ma": "CEF",
                                       "springfield-mo": "SGF",
                                       "st-augustine": "UST",
                                       "st-cloud": "STC",
                                       "st-george": "SGU",
                                       "stillwater": "SWO",
                                       "stockton": "SCK",
                                       "sudbury": "YSB",
                                       "syracuse": "SYR",
                                       "tallahassee": "TLH",
                                       "tampa": "TPA",
                                       "terre-haute": "HUF",
                                       "territories": "YZF",
                                       "texarkana": "TXK",
                                       "thunder-bay": "YQT",
                                       "toledo": "TOL",
                                       "topeka": "FOE",
                                       "toronto": "YYZ",
                                       "treasure-coast": "VRB",
                                       "tucson": "TUS",
                                       "tulsa": "TUL",
                                       "tuscaloosa": "TCL",
                                       "twin-falls": "TWF",
                                       "tyler": "TYR",
                                       "utica": "UCA",
                                       "valdosta": "VLD",
                                       "vancouver": "YVR",
                                       "ventura-county": "OXR",
                                       "vermont": "BTV",
                                       "victoria": "YYJ",
                                       "victoria-tx": "VCT",
                                       "virginia-beach": "ORF",
                                       "visalia-tulare": "VIS",
                                       "waco": "ACT",
                                       "washington-dc": "IAD",
                                       "waterloo": "ALO",
                                       "watertown": "ART",
                                       "wausau": "AUW",
                                       "wenatchee": "EAT",
                                       "west-palm-beach": "PBI",
                                       "wheeling-wv": "HLG",
                                       "whistler": "YWS",
                                       "wichita": "ICT",
                                       "wichita-falls": "SPS",
                                       "williamsport": "IPT",
                                       "wilmington-nc": "ILM",
                                       "windsor": "YQG",
                                       "winnipeg": "YWG",
                                       "winston-salem": "INT",
                                       "worcester": "ORH",
                                       "wyoming": "CPR",
                                       "yakima": "YKM",
                                       "york-pa": "THV",
                                       "youngstown": "YNG",
                                       "yuba-sutter": "MYV",
                                       "yuma": "YUM"}

def myproviderguide_url_to_sitekey(url):
    """http://longisland.myproviderguide.com/FemaleEscorts/s-mny-oo-chics-but-oo-nn-lik-oo-me-19/40317377"""
    (scheme, netloc, path, params, query, fragment) = urlparse(url)
    dirs = path.split('/')
    return dirs[2]

def dtMktMyproviderguide(url, title, city, state):
    return mkSrcMktUri("url", "myproviderguide", myproviderguide_url_to_sitekey(url)])

### CRAIGSLIST

craigslist_sitekey_to_marketid = {
    "abbotsford": "YXX",
    "aberdeen": "ABZ",
    "abilene": "ABI",
    "acapulco": "ACA",
    "accra": "ACC",
    "addisababa": "ADD",
    "adelaide": "ADL",
    "ahmedabad": "AMD",
    "akroncanton": "CAK",
    "albany": "ALB",
    "albanyga": "ABY",
    "albuquerque": "ABQ",
    "alicante": "ALC",
    "allentown": "ABE",
    "altoona": "AOO",
    "amarillo": "AMA",
    "ames": "AMW",
    "amsterdam": "AMS",
    "anchorage": "ANC",
    "annapolis": "ANP",
    "annarbor": "ARB",
    "appleton": "ATW",
    "asheville": "AVL",
    "ashtabula": "HZY",
    "athens": "ATH",
    "athensga": "AHN",
    "athensohio": "ATO",
    "atlanta": "ATL",
    "auburn": "AUO",
    "auckland": "AKL",
    "augusta": "AGS",
    "austin": "AUS",
    "bacolod": "BCD",
    "baghdad": "BGW",
    "bajasur": "SJD",
    "bakersfield": "BFL",
    "baleares": "PMI",
    "baltimore": "BWI",
    "bangalore": "BLR",
    "bangkok": "BKK",
    "bangladesh": "DAC",
    "barcelona": "BCN",
    "barrie": "QEB",
    "basel": "BSL",
    "bath": "BRS",
    "batonrouge": "BTR",
    "battlecreek": "AZO",
    "beaumont": "BPT",
    "beijing": "PEK",
    "beirut": "BEY",
    "belfast": "BFS",
    "belleville": "YTR",
    "bellingham": "BLI",
    "belohorizonte": "CNF",
    "bemidji": "BJI",
    "bend": "",
    "berlin": "TXL",
    "bern": "BRN",
    "bgky": "BWG",
    "bham": "BHM",
    "bhubaneswar": "BBI",
    "bigbend": "ALE",
    "bilbao": "BIO",
    "billings": "BIL",
    "binghamton": "BGM",
    "birmingham": "BHX",
    "bismarck": "BIS",
    "blacksburg": "BCB",
    "bloomington": "BMG",
    "bn": "BMI",
    "boise": "BOI",
    "bologna": "BLQ",
    "boone": "NC06",
    "bordeaux": "BOD",
    "boston": "BOS",
    "boulder": "WBU",
    "bozeman": "BZN",
    "brainerd": "BRD",
    "brantford": "YFD",
    "brasilia": "BSB",
    "bremen": "BRE",
    "brighton": "ESH",
    "brisbane": "BNE",
    "bristol": "BRS",
    "brownsville": "BRO",
    "brunswick": "BQK",
    "brussels": "BRU",
    "bucharest": "OTP",
    "budapest": "BUD",
    "buenosaires": "EZE",
    "buffalo": "BUF",
    "bulgaria": "SOF",
    "burlington": "BTV",
    "butte": "BTM",
    "cadiz": "XRY",
    "cairns": "CNS",
    "cairo": "CAI",
    "calgary": "YYC",
    "cambridge": "CBG",
    "canarias": "TFS",
    "canberra": "CBR",
    "capecod": "PVC",
    "capetown": "CPT",
    "caracas": "CCS",
    "carbondale": "MDH",
    "cardiff": "CWL",
    "caribbean": "KIN",
    "cariboo": "YXS",
    "casablanca": "CMN",
    "catskills": "20N",
    "cdo": "CGY",
    "cebu": "CEB",
    "cedarrapids": "CID",
    "cenla": "ESF",
    "centralmich": "LAN",
    "cfl": "SEF",
    "chambana": "CMI",
    "chambersburg": "N68",
    "chandigarh": "IXC",
    "charleston": "CHS",
    "charlestonwv": "CRW",
    "charlotte": "CLT",
    "charlottesville": "CHO",
    "chatham": "XCM",
    "chattanooga": "CHA",
    "chautauqua": "JHW",
    "chengdu": "CTU",
    "chennai": "MAA",
    "chicago": "ORD",
    "chico": "CIC",
    "chihuahua": "CUU",
    "chillicothe": "RZT",
    "chongqing": "CKG",
    "christchurch": "CHC",
    "cincinnati": "CVG",
    "clarksville": "CKV",
    "cleveland": "CLE",
    "clovis": "CVN",
    "cnj": "47N",
    "collegestation": "CLL",
    "cologne": "CGN",
    "colombia": "BOG",
    "columbia": "CAE",
    "columbiamo": "COU",
    "columbus": "CMH",
    "columbusga": "CSG",
    "comoxvalley": "YQQ",
    "cookeville": "SRB",
    "copenhagen": "CPH",
    "cornwall": "YCC",
    "corpuschristi": "CRP",
    "corvallis": "CVO",
    "cosprings": "COS",
    "costarica": "SJO",
    "cotedazur": "NCE",
    "coventry": "CVT",
    "cranbrook": "YXC",
    "csd": "PIR",
    "curitiba": "CWB",
    "dalian": "DLC",
    "dallas": "DFW",
    "danville": "DAN",
    "darwin": "DRW",
    "davaocity": "DVO",
    "dayton": "DAY",
    "daytona": "DAB",
    "decatur": "DEC",
    "delaware": "ILG",
    "delhi": "DEL",
    "delrio": "DRT",
    "denver": "DEN",
    "derby": "EMA",
    "desmoines": "DSM",
    "detroit": "DTW",
    "devon": "EXT",
    "dothan": "DHN",
    "dresden": "DRS",
    "dubai": "DXB",
    "dublin": "DUB",
    "dubuque": "DBQ",
    "duluth": "DLH",
    "dundee": "DND",
    "dunedin": "DUD",
    "durban": "DUR",
    "dusseldorf": "DUS",
    "eastco": "LIC",
    "easternshore": "SBY",
    "eastidaho": "IDA",
    "eastky": "PBX",
    "eastmids": "EMA",
    "eastnc": "PGV",
    "eastoregon": "PDT",
    "easttexas": "TYR",
    "eauclaire": "EAU",
    "edinburgh": "EDI",
    "edmonton": "YEG",
    "elko": "EKO",
    "elmira": "ELM",
    "elpaso": "ELP",
    "elsalvador": "SAL",
    "enid": "END",
    "erie": "ERI",
    "essen": "ESS",
    "essex": "STN",
    "eugene": "EUG",
    "evansville": "EVV",
    "fairbanks": "FAI",
    "fargo": "FAR",
    "farmington": "FMN",
    "faro": "FAO",
    "fayar": "XNA",
    "fayetteville": "FAY",
    "fingerlakes": "D82",
    "flagstaff": "FLG",
    "flint": "FNT",
    "florence": "FLR",
    "florencesc": "FLO",
    "fortaleza": "FOR",
    "fortcollins": "FNL",
    "fortdodge": "FOD",
    "fortlauderdale": "FLL",
    "fortmyers": "RSW",
    "fortsmith": "FSM",
    "fortwayne": "FWA",
    "frankfurt": "FRA",
    "frederick": "FDK",
    "fredericksburg": "EZF",
    "fresno": "FAT",
    "ftmcmurray": "YMM",
    "fukuoka": "FUK",
    "gadsden": "GAD",
    "gainesville": "GNV",
    "galveston": "GLS",
    "geneva": "GVA",
    "genoa": "GOA",
    "glasgow": "GLA",
    "glensfalls": "GFL",
    "goa": "GOI",
    "goldcoast": "OOL",
    "goldcountry": "O22",
    "granada": "GRX",
    "grandforks": "GFK",
    "grandisland": "GRI",
    "grandrapids": "GRR",
    "greatfalls": "GTF",
    "greenbay": "GRB",
    "greensboro": "GSO",
    "greenville": "GSP",
    "grenoble": "GNB",
    "guadalajara": "GDL",
    "guanajuato": "BJX",
    "guangzhou": "CAN",
    "guatemala": "GUA",
    "guelph": "",
    "gulfport": "GPT",
    "haifa": "HFA",
    "halifax": "YHZ",
    "hamburg": "HAM",
    "hamilton": "YHM",
    "hampshire": "SOU",
    "hanford": "HJO",
    "hangzhou": "HGH",
    "hannover": "HAJ",
    "harrisburg": "MDT",
    "harrisonburg": "SHD",
    "hartford": "HFD",
    "hat": "YXH",
    "hattiesburg": "HBG",
    "heidelberg": "HDB",
    "helena": "HLN",
    "helsinki": "HEL",
    "hermosillo": "HMO",
    "hickory": "HKY",
    "hiltonhead": "HHH",
    "hiroshima": "HIJ",
    "hobart": "HBA",
    "holland": "BIV",
    "hongkong": "HKG",
    "honolulu": "HNL",
    "houma": "HUM",
    "houston": "IAH",
    "hudsonvalley": "SWF",
    "humboldt": "ACV",
    "huntington": "HTS",
    "huntsville": "HSV",
    "hyderabad": "HYD",
    "iloilo": "ILO",
    "imperial": "IPL",
    "indianapolis": "IND",
    "indore": "IDR",
    "inlandempire": "ONT",
    "iowacity": "IOW",
    "istanbul": "IST",
    "ithaca": "ITH",
    "jackson": "JAN",
    "jacksontn": "MKL",
    "jacksonville": "JAX",
    "jaipur": "JAI",
    "jakarta": "CGK",
    "janesville": "JVL",
    "jerseyshore": "ACY",
    "jerusalem": "",
    "johannesburg": "JNB",
    "jonesboro": "JBR",
    "joplin": "JLN",
    "juarez": "CJS",
    "juneau": "JNU",
    "jxn": "JXN",
    "kaiserslautern": "RMS",
    "kalamazoo": "AZO",
    "kalispell": "FCA",
    "kamloops": "YKA",
    "kansascity": "MCI",
    "kelowna": "YLW",
    "kenai": "ENA",
    "kent": "LYX",
    "kenya": "NBO",
    "kerala": "TRV",
    "keys": "EYW",
    "killeen": "GRK",
    "kingston": "YGK",
    "kirksville": "IRK",
    "kitchener": "YKF",
    "klamath": "LMT",
    "knoxville": "TYS",
    "kokomo": "OKK",
    "kolkata": "CCU",
    "kpr": "PSC",
    "ksu": "MHK",
    "kuwait": "KWI",
    "lacrosse": "LSE",
    "lafayette": "LFT",
    "lakecharles": "LCH",
    "lakecity": "LCQ",
    "lakeland": "LAL",
    "lancaster": "LNS",
    "lansing": "LAN",
    "lapaz": "LPB",
    "laredo": "LRD",
    "lasalle": "VYS",
    "lascruces": "LRU",
    "lasvegas": "LAS",
    "lausanne": "",
    "lawrence": "LWC",
    "lawton": "LAW",
    "leeds": "LBA",
    "leipzig": "LEJ",
    "lethbridge": "YQL",
    "lewiston": "LWS",
    "lexington": "LEX",
    "lille": "LIL",
    "lima": "LIM",
    "limaohio": "AOH",
    "lincoln": "LNK",
    "lisbon": "LIS",
    "littlerock": "LIT",
    "liverpool": "LPL",
    "logan": "LGU",
    "loire": "NTE",
    "london": "LHR",
    "londonon": "YXU",
    "longisland": "ISP",
    "losangeles": "LAX",
    "louisville": "SDF",
    "loz": "AIZ",
    "lubbock": "LBB",
    "lucknow": "LKO",
    "luxembourg": "LUX",
    "lynchburg": "LYH",
    "lyon": "LYS",
    "macon": "MCN",
    "madison": "MSN",
    "madrid": "MAD",
    "maine": "PWM",
    "malaga": "AGP",
    "malaysia": "KUL",
    "managua": "MGA",
    "manchester": "MAN",
    "manila": "MNL",
    "mankato": "MKT",
    "mansfield": "MFD",
    "marseilles": "MRS",
    "marshall": "MML",
    "martinsburg": "MRB",
    "masoncity": "MCW",
    "mattoon": "MTO",
    "mazatlan": "MZT",
    "mcallen": "MFE",
    "meadville": "GKJ",
    "medford": "MFR",
    "melbourne": "MEL",
    "memphis": "MEM",
    "mendocino": "UKI",
    "merced": "MCE",
    "meridian": "MEI",
    "mexicocity": "MEX",
    "miami": "MIA",
    "micronesia": "GUM",
    "micronesia": "GUM",
    "milan": "MXP",
    "milwaukee": "MKE",
    "minneapolis": "MSP",
    "missoula": "MSO",
    "mobile": "MOB",
    "modesto": "MOD",
    "mohave": "IFP",
    "monroe": "MLU",
    "monroemi": "TTF",
    "montana": "GDV",
    "monterey": "MRY",
    "monterrey": "MTY",
    "montevideo": "MVD",
    "montgomery": "MGM",
    "montpellier": "MPL",
    "montreal": "YUL",
    "morgantown": "MGW",
    "moscow": "SVO",
    "moseslake": "MWH",
    "mumbai": "BOM",
    "muncie": "MIE",
    "munich": "MUC",
    "muskegon": "MKG",
    "myrtlebeach": "MYR",
    "nacogdoches": "OCH",
    "naga": "WNP",
    "nagoya": "NGO",
    "nanaimo": "YCD",
    "nanjing": "NKG",
    "naples": "NAP",
    "nashville": "BNA",
    "natchez": "HEZ",
    "nd": "MOT",
    "nesd": "ATY",
    "newbrunswick": "YQM",
    "newcastle": "NCL",
    "newfoundland": "YYT",
    "newhaven": "HVN",
    "newjersey": "EWR",
    "newlondon": "GON",
    "neworleans": "MSY",
    "newyork": "JFK",
    "nh": "MHT",
    "niagara": "YCM",
    "nmi": "TVC",
    "norfolk": "ORF",
    "northernwi": "EAU",
    "northmiss": "TUP",
    "northplatte": "LBF",
    "norwich": "NWI",
    "nottingham": "NQT",
    "ntl": "NTL",
    "nuremberg": "NUE",
    "nwct": "DXR",
    "nwga": "RMG",
    "nwks": "GLD",
    "oaxaca": "OAX",
    "ocala": "OCF",
    "odessa": "MAF",
    "ogden": "OGD",
    "okaloosa": "VPS",
    "okinawa": "OKA",
    "oklahomacity": "OKC",
    "olympic": "CLM",
    "omaha": "OMA",
    "oneonta": "ONH",
    "onslow": "OAJ",
    "orangecounty": "SNA",
    "oregoncoast": "ONP",
    "orlando": "MCO",
    "osaka": "KIX",
    "oslo": "OSL",
    "ottawa": "YOW",
    "ottumwa": "OTM",
    "outerbanks": "FFA",
    "owensboro": "OWB",
    "owensound": "YOS",
    "oxford": "OXF",
    "pakistan": "KHI",
    "palmsprings": "PSP",
    "pampanga": "CRK",
    "panama": "PAC",
    "panamacity": "PFN",
    "paris": "CDG",
    "parkersburg": "PKB",
    "peace": "YPE",
    "pei": "YYG",
    "pennstate": "UNV",
    "pensacola": "PNS",
    "peoria": "PIA",
    "perth": "PER",
    "perugia": "PEG",
    "peterborough": "YPQ",
    "philadelphia": "PHL",
    "phoenix": "PHX",
    "pittsburgh": "PIT",
    "plattsburgh": "PBG",
    "poconos": "MPO",
    "porthuron": "PHN",
    "portland": "PDX",
    "porto": "OPO",
    "portoalegre": "POA",
    "potsdam": "MSS",
    "prague": "PRG",
    "prescott": "PRC",
    "pretoria": "PRY",
    "princegeorge": "YXS",
    "providence": "PVD",
    "provo": "PVU",
    "puebla": "PBC",
    "pueblo": "PUB",
    "puertorico": "SJU",
    "puertorico": "SJU",
    "pullman": "PUW",
    "pune": "PNQ",
    "pv": "PVR",
    "quadcities": "MLI",
    "quebec": "YQB",
    "quincy": "UIN",
    "quito": "UIO",
    "racine": "RAC",
    "raleigh": "RDU",
    "ramallah": "JRS",
    "rapidcity": "RAP",
    "reading": "RDG",
    "recife": "REC",
    "reddeer": "YQF",
    "redding": "RDD",
    "regina": "YQR",
    "rennes": "RNS",
    "reno": "RNO",
    "reykjavik": "RKV",
    "richmond": "RIC",
    "richmondin": "RID",
    "rio": "GIG",
    "rmn": "RST",
    "roanoke": "ROA",
    "rochester": "ROC",
    "rockford": "RFD",
    "rockies": "EGE",
    "rome": "FCO",
    "roseburg": "RBG",
    "roswell": "ROW",
    "rouen": "URO",
    "sacramento": "SMF",
    "saginaw": "MBS",
    "saguenay": "YBG",
    "salem": "SLE",
    "salina": "SLN",
    "saltlakecity": "SLC",
    "salvador": "SSA",
    "sanangelo": "SJT",
    "sanantonio": "SAT",
    "sandiego": "SAN",
    "sandusky": "SKY",
    "sanmarcos": "HYI",
    "santabarbara": "SBA",
    "santafe": "SAF",
    "santamaria": "SMX",
    "santiago": "SCL",
    "santodomingo": "SDQ",
    "saopaulo": "GRU",
    "sapporo": "CTS",
    "sarasota": "SRQ",
    "sardinia": "CAG",
    "sarnia": "YZR",
    "saskatoon": "YXE",
    "savannah": "SAV",
    "scottsbluff": "BFF",
    "scranton": "AVP",
    "sd": "PIR",
    "seattle": "SEA",
    "seks": "FSK",
    "semo": "CGI",
    "sendai": "SDJ",
    "seoul": "ICN",
    "sevilla": "SVQ",
    "sfbay": "SFO",
    "shanghai": "SHA",
    "sheboygan": "SBM",
    "sheffield": "DSA",
    "shenyang": "SHE",
    "shenzhen": "SZX",
    "sherbrooke": "YSC",
    "shoals": "MSL",
    "showlow": "SOW",
    "shreveport": "SHV",
    "sicily": "PMO",
    "sierravista": "FHU",
    "singapore": "SIN",
    "siouxcity": "SUX",
    "siouxfalls": "FSD",
    "siskiyou": "SIY",
    "skagit": "BVS",
    "skeena": "YYD",
    "slo": "SBP",
    "smd": "2W6",
    "soo": "YAM",
    "southbend": "SBN",
    "southcoast": "EWB",
    "southjersey": "MIV",
    "spacecoast": "TIX",
    "spokane": "GEG",
    "springfield": "SGF",
    "springfieldil": "SPI",
    "statesboro": "TBR",
    "staugustine": "UST",
    "stcloud": "STC",
    "stgeorge": "SGU",
    "stillwater": "SWO",
    "stjoseph": "STJ",
    "stlouis": "STL",
    "stockholm": "ARN",
    "stockton": "SCK",
    "stpetersburg": "LED",
    "strasbourg": "SXB",
    "stuttgart": "STR",
    "sudbury": "YSB",
    "sunshine": "YHS",
    "surat": "STV",
    "susanville": "SVE",
    "swks": "GCK",
    "swmi": "BEH",
    "swv": "BKW",
    "swva": "MKJ",
    "sydney": "SYD",
    "syracuse": "SYR",
    "taipei": "TPE",
    "tallahassee": "TLH",
    "tampa": "TPA",
    "tehran": "IKA",
    "telaviv": "TLV",
    "terrehaute": "HUF",
    "territories": "YZF",
    "texarkana": "TXK",
    "texoma": "GYI",
    "thumb": "PHN",
    "thunderbay": "YQT",
    "tijuana": "TIJ",
    "tippecanoe": "LAF",
    "tokyo": "NRT",
    "toledo": "TOL",
    "topeka": "FOE",
    "torino": "TRN",
    "toronto": "YYZ",
    "toulouse": "TLS",
    "treasure": "VRB",
    "tricities": "TRI",
    "troisrivieres": "YRQ",
    "tucson": "TUS",
    "tulsa": "TUL",
    "tunis": "TUN",
    "tuscaloosa": "TCL",
    "tuscarawas": "PHD",
    "twinfalls": "TWF",
    "twintiers": "OLE",
    "ukraine": "IEV",
    "up": "MQT",
    "utica": "UCA",
    "valdosta": "VLD",
    "valencia": "VLC",
    "vancouver": "YVR",
    "venice": "VCE",
    "ventura": "OXR",
    "veracruz": "VER",
    "victoria": "YYJ",
    "victoriatx": "VCT",
    "vienna": "VIE",
    "vietnam": "SGN",
    "virgin": "STT",
    "virgin": "STT",
    "visalia": "VIS",
    "waco": "ACT",
    "warsaw": "WAW",
    "washingtondc": "IAD",
    "waterloo": "ALO",
    "watertown": "ART",
    "wausau": "AUW",
    "wellington": "WLG",
    "wenatchee": "EAT",
    "westernmass": "CEF",
    "westky": "PAH",
    "westmd": "CBE",
    "westslope": "GJT",
    "wheeling": "HLG",
    "whistler": "YWS",
    "whitehorse": "YXY",
    "wichita": "ICT",
    "wichitafalls": "SPS",
    "williamsport": "IPT",
    "wilmington": "ILM",
    "winchester": "OKV",
    "windsor": "YQG",
    "winnipeg": "YWG",
    "winstonsalem": "INT",
    "wollongong": "WOL",
    "worcester": "ORH",
    "wuhan": "WUH",
    "wv": "CRW",
    "wyoming": "CPR",
    "xian": "XIY",
    "yakima": "YKM",
    "yellowknife": "YZF",
    "york": "THV",
    "youngstown": "YNG",
    "yubasutter": "MYV",
    "yucatan": "MID",
    "yuma": "YUM",
    "zagreb": "ZAG",
    "zamboanga": "ZAM",
    "zanesville": "ZZV"}

def craigslist_url_to_sitekey(url):
    """http://longisland.craigslist.com/FemaleEscorts/s-mny-oo-chics-but-oo-nn-lik-oo-me-19/40317377"""
    (scheme, netloc, path, params, query, fragment) = urlparse(url)
    sitekey = netloc.split('.')[0]
    return sitekey

def dtMktCraigslist(url, title, city, state):
    return mkSrcMktUri("url", "craigslist", craigslist_url_to_sitekey(url)])

### CLASSIVOX

classivox_sitekey_to_marketid = {
                                 "abilene": "ABI",
                                 "akron": "CAK",
                                 "albany": "ALB",
                                 "albany-ga": "ABY",
                                 "albuquerque": "ABQ",
                                 "altoona": "AOO",
                                 "amarillo": "AMA",
                                 "ames": "AMW",
                                 "anchorage": "ANC",
                                 "ann-arbor": "ARB",
                                 "annapolis": "ANP",
                                 "appleton": "ATW",
                                 "asheville": "AVL",
                                 "ashtabula": "HZY",
                                 "athens": "AHN",
                                 "athens-oh": "ATO",
                                 "atlanta": "ATL",
                                 "auburn": "AUO",
                                 "augusta": "AGS",
                                 "austin": "AUS",
                                 "bakersfield": "BFL",
                                 "baltimore": "BWI",
                                 "baton-rouge": "BTR",
                                 "battle-creek": "AZO",
                                 "beaumont": "BPT",
                                 "bellingham": "BLI",
                                 "bemidji": "BJI",
                                 "bend": "RDM",
                                 "billings": "BIL",
                                 "binghamton": "BGM",
                                 "birmingham-al": "BHM",
                                 "bismarck": "BIS",
                                 "bloomington": "BMI",
                                 "bloomington-in": "BMG",
                                 "boise": "BOI",
                                 "boone": "NC06",
                                 "boston": "BOS",
                                 "boulder": "WBU",
                                 "bowling-green": "BWG",
                                 "bozeman": "BZN",
                                 "broward-county": "MIA",
                                 "brownsville": "BRO",
                                 "brunswick": "BQK",
                                 "buffalo": "BUF",
                                 "burlington": "BTV",
                                 "calgary": "YYC",
                                 "cape-cod": "PVC",
                                 "catskills": "20N",
                                 "cedar-rapids": "CID",
                                 "central-mi": "LAN",
                                 "central-nj": "47N",
                                 "charleston": "CHS",
                                 "charleston-wv": "CRW",
                                 "charlotte": "CLT",
                                 "charlottesville": "CHO",
                                 "chattanooga": "CHA",
                                 "chautauqua": "JHW",
                                 "chicago": "ORD",
                                 "chico": "CIC",
                                 "chillicothe": "RZT",
                                 "cincinnati": "CVG",
                                 "clarksville": "CKV",
                                 "cleveland": "CLE",
                                 "clovis": "CVN",
                                 "college-station": "CLL",
                                 "colorado-springs": "COS",
                                 "columbia": "COU",
                                 "columbia-sc": "CAE",
                                 "columbus": "CMH",
                                 "columbus-oh": "CMH",
                                 "comox-valley": "YQQ",
                                 "cookeville": "SRB",
                                 "corpus-christi": "CRP",
                                 "corvallis": "CVO",
                                 "cumberland": "CBE",
                                 "dallas-ft-worth": "DFW",
                                 "danville": "DAN",
                                 "dayton": "DAY",
                                 "daytona-beach": "DAB",
                                 "decatur": "DEC",
                                 "del-rio": "DRT",
                                 "delaware": "ILG",
                                 "denver": "DEN",
                                 "des-moines": "DSM",
                                 "detroit": "DTW",
                                 "dothan": "DHN",
                                 "dubuque": "DBQ",
                                 "duluth": "DLH",
                                 "east-oregon": "PDT",
                                 "eastern-co": "LIC",
                                 "eastern-ct": "GON",
                                 "eastern-ky": "PBX",
                                 "eastern-nc": "PGV",
                                 "eastern-panhandle": "MRB",
                                 "eastern-shore": "SBY",
                                 "eau-claire": "EAU",
                                 "edmonton": "YEG",
                                 "el-paso": "ELP",
                                 "elko": "EKO",
                                 "elmira": "ELM",
                                 "erie": "ERI",
                                 "eugene": "EUG",
                                 "evansville": "EVV",
                                 "fairbanks": "FAI",
                                 "fargo": "FAR",
                                 "farmington": "FMN",
                                 "fayetteville": "XNA",
                                 "fayetteville-nc": "FAY",
                                 "flagstaff-sedona": "FLG",
                                 "flint": "FNT",
                                 "florence": "FLO",
                                 "florence-muscle-shoals": "MSL",
                                 "florida-keys": "EYW",
                                 "fort-collins": "FNL",
                                 "fort-dodge": "FOD",
                                 "fort-lauderdale": "FLL",
                                 "fort-smith": "FSM",
                                 "fort-wayne": "FWA",
                                 "frederick": "FDK",
                                 "fredericksburg-va": "EZF",
                                 "fresno-madera": "FAT",
                                 "ft-mcmurray": "YMM",
                                 "gadsden-anniston": "GAD",
                                 "gainesville": "GNV",
                                 "galveston": "GLS",
                                 "glens-falls": "GFL",
                                 "gold-country": "O22",
                                 "grand-forks": "GFK",
                                 "grand-island": "GRI",
                                 "grand-rapids": "GRR",
                                 "green-bay": "GRB",
                                 "greensboro": "GSO",
                                 "greenville": "GSP",
                                 "guelph": "CNC4",
                                 "gulfport": "GPT",
                                 "hamilton-burlington": "YHM",
                                 "hampton-roads": "ORF",
                                 "hanford-corcoran": "HJO",
                                 "harrisburg": "MDT",
                                 "harrisonburg": "SHD",
                                 "hartford": "HFD",
                                 "hattiesburg": "HBG",
                                 "hickory": "HKY",
                                 "high-rockies": "EGE",
                                 "hilton-head": "HHH",
                                 "holland": "BIV",
                                 "honolulu": "HNL",
                                 "houma": "HUM",
                                 "houston": "IAH",
                                 "hudson-valley": "SWF",
                                 "humboldt-county": "ACV",
                                 "huntington": "HTS",
                                 "huntsville-decatur": "HSV",
                                 "imperial-county": "IPL",
                                 "indianapolis": "IND",
                                 "inland-empire": "ONT",
                                 "iowa-city": "IOW",
                                 "ithaca": "ITH",
                                 "jackson": "JAN",
                                 "jackson-tn": "MKL",
                                 "jacksonville": "JAX",
                                 "jacksonville-nc": "OAJ",
                                 "janesville": "JVL",
                                 "jersey-shore": "ACY",
                                 "jonesboro": "JBR",
                                 "joplin": "JLN",
                                 "kalamazoo": "AZO",
                                 "kansas-city": "MCI",
                                 "kenai-peninsula": "ENA",
                                 "kennewick": "PSC",
                                 "kenosha": "RAC",
                                 "killeen": "GRK",
                                 "kirksville": "IRK",
                                 "klamath-falls": "LMT",
                                 "knoxville": "TYS",
                                 "kokomo": "OKK",
                                 "lafayette": "LAF",
                                 "lafayette-la": "LAF",
                                 "lakeland": "LAL",
                                 "lancaster": "LNS",
                                 "lansing": "LAN",
                                 "laredo": "LRD",
                                 "las-cruces": "LRU",
                                 "las-vegas": "LAS",
                                 "lawrence": "LWC",
                                 "lawton": "LAW",
                                 "lehigh-valley": "ABE",
                                 "lethbridge": "YQL",
                                 "lewiston": "LWS",
                                 "lexington": "LEX",
                                 "lima-oh": "AOH",
                                 "lincoln": "LNK",
                                 "little-rock": "LIT",
                                 "logan": "LGU",
                                 "london-on": "YXU",
                                 "long-island": "ISP",
                                 "los-angeles": "LAX",
                                 "louisville": "SDF",
                                 "lubbock": "LBB",
                                 "lynchburg": "LYH",
                                 "macon": "MCN",
                                 "madison": "MSN",
                                 "maine": "PWM",
                                 "manhattan": "JFK",
                                 "mankato": "MKT",
                                 "mansfield": "MFD",
                                 "mason-city": "MCW",
                                 "mattoon": "MTO",
                                 "mcallen": "MFE",
                                 "medford": "MFR",
                                 "medicine-hat": "YXH",
                                 "memphis": "MEM",
                                 "mendocino-county": "UKI",
                                 "merced": "MCE",
                                 "miami-dade": "MIA",
                                 "milwaukee": "MKE",
                                 "minneapolis": "MSP",
                                 "mobile": "MOB",
                                 "modesto": "MOD",
                                 "mohave-county": "IFP",
                                 "monroe": "MLU",
                                 "monroe-mi": "TTF",
                                 "monterey-bay": "MRY",
                                 "montgomery": "MGM",
                                 "montreal": "YUL",
                                 "morgantown": "MGW",
                                 "moses-lake": "MWH",
                                 "muncie": "MIE",
                                 "muskegon": "MKG",
                                 "myrtle-beach": "MYR",
                                 "nanaimo": "YCD",
                                 "nashville": "BNA",
                                 "new-hampshire": "MHT",
                                 "new-haven": "HVN",
                                 "new-orleans": "MSY",
                                 "new-river-valley": "BCB",
                                 "new-york-city": "JFK",
                                 "niagara": "YCM",
                                 "north-dakota": "FAR",
                                 "north-jersey": "EWR",
                                 "north-ms": "TUP",
                                 "north-panhandle": "HLG",
                                 "north-platte": "LBF",
                                 "northern-mi": "TVC",
                                 "northern-wi": "EAU",
                                 "northwest-ct": "DXR",
                                 "northwest-ga": "RMG",
                                 "ocala": "OCF",
                                 "odessa": "MAF",
                                 "ogden": "OGD",
                                 "okaloosa": "VPS",
                                 "oklahoma-city": "OKC",
                                 "old-west-virginia": "CRW",
                                 "omaha": "OMA",
                                 "oneonta": "ONH",
                                 "orange-county": "SNA",
                                 "oregon-coast": "ONP",
                                 "orlando": "MCO",
                                 "outer-banks": "FFA",
                                 "owen-sound": "YOS",
                                 "owensboro": "OWB",
                                 "ozarks": "AIZ",
                                 "palm-beach-county": "PBI",
                                 "palm-springs": "PSP",
                                 "panama-city": "PFN",
                                 "parkersburg": "PKB",
                                 "peace-river-country": "YPE",
                                 "pensacola": "PNS",
                                 "peoria": "PIA",
                                 "philadelphia": "PHL",
                                 "phoenix": "PHX",
                                 "pittsburgh": "PIT",
                                 "plattsburgh": "PBG",
                                 "poconos": "MPO",
                                 "portland": "PDX",
                                 "potsdam": "MSS",
                                 "prescott": "PRC",
                                 "provo": "PVU",
                                 "pueblo": "PUB",
                                 "pullman": "PUW",
                                 "quad-cities": "MLI",
                                 "quebec-city": "YQB",
                                 "queens": "JFK",
                                 "raleigh": "RDU",
                                 "reading": "RDG",
                                 "red-deer": "YQF",
                                 "redding": "RDD",
                                 "regina": "YQR",
                                 "reno": "RNO",
                                 "richmond": "RID",
                                 "roanoke": "ROA",
                                 "rochester": "RST",
                                 "rochester-ny": "ROC",
                                 "rockford": "RFD",
                                 "roseburg": "RBG",
                                 "roswell": "ROW",
                                 "sacramento": "SMF",
                                 "saginaw": "MBS",
                                 "salem": "SLE",
                                 "salina": "SLN",
                                 "salt-lake-city": "SLC",
                                 "san-angelo": "SJT",
                                 "san-antonio": "SAT",
                                 "san-diego": "SAN",
                                 "san-francisco": "SFO",
                                 "san-luis-obispo": "SBP",
                                 "san-marcos": "HYI",
                                 "sandusky": "SKY",
                                 "santa-barbara": "SBA",
                                 "santa-fe": "SAF",
                                 "santa-maria": "SMX",
                                 "sarasota": "SRQ",
                                 "savannah": "SAV",
                                 "scottsbluff": "BFF",
                                 "scranton": "AVP",
                                 "seattle-tacoma": "SEA",
                                 "sheboygan": "SBM",
                                 "show-low": "SOW",
                                 "shreveport": "SHV",
                                 "sierra-vista": "FHU",
                                 "sioux-city": "SUX",
                                 "siskiyou-county": "SIY",
                                 "south-bend": "SBN",
                                 "south-coast": "EWB",
                                 "south-dakota": "PIR",
                                 "south-jersey": "MIV",
                                 "south-wv": "BKW",
                                 "southeast-alaska": "JNU",
                                 "southeast-mo": "CGI",
                                 "southern-il": "MDH",
                                 "southern-md": "2W6",
                                 "southwest-mn": "MML",
                                 "southwest-va": "MKJ",
                                 "space-coast": "TIX",
                                 "spokane": "GEG",
                                 "springfield": "SPI",
                                 "springfield-mo": "SGF",
                                 "st-augustine": "UST",
                                 "st-cloud": "STC",
                                 "st-george": "SGU",
                                 "st-joseph": "STJ",
                                 "st-louis": "STL",
                                 "state-college": "UNV",
                                 "statesboro": "TBR",
                                 "stillwater": "SWO",
                                 "stockton": "SCK",
                                 "susanville": "SVE",
                                 "syracuse": "SYR",
                                 "tallahassee": "TLH",
                                 "tampa-bay": "TPA",
                                 "terre-haute": "HUF",
                                 "texarkana": "TXK",
                                 "texoma": "GYI",
                                 "toledo": "TOL",
                                 "topeka": "FOE",
                                 "toronto": "YYZ",
                                 "treasure-coast": "VRB",
                                 "tri-cities": "TRI",
                                 "tucson": "TUS",
                                 "tulsa": "TUL",
                                 "tuscaloosa": "TCL",
                                 "twin-falls": "TWF",
                                 "tyler": "TYR",
                                 "utica": "UCA",
                                 "valdosta": "VLD",
                                 "ventura-county": "OXR",
                                 "victoria-tx": "VCT",
                                 "visalia-tulare": "VIS",
                                 "waco": "ACT",
                                 "washington-dc": "IAD",
                                 "waterloo": "YKF",
                                 "watertown": "ART",
                                 "wausau": "AUW",
                                 "wenatchee": "EAT",
                                 "west-palm-beach": "PBI",
                                 "western-il": "UIN",
                                 "western-ky": "PAH",
                                 "western-ma": "CEF",
                                 "western-md": "CBE",
                                 "western-slope": "GJT",
                                 "wichita": "ICT",
                                 "wichita-falls": "SPS",
                                 "williamsport": "IPT",
                                 "wilmington": "ILG",
                                 "winchester": "OKV",
                                 "winnipeg": "YWG",
                                 "winston-salem": "INT",
                                 "worcester": "ORH",
                                 "yakima": "YKM",
                                 "york": "THV",
                                 "youngstown": "YNG",
                                 "yuma": "YUM",
                                 "zanesville": "ZZV"}

def classivox_url_to_sitekey(url):
    """http://longisland.classivox.com/FemaleEscorts/s-mny-oo-chics-but-oo-nn-lik-oo-me-19/40317377"""
    (scheme, netloc, path, params, query, fragment) = urlparse(url)
    sitekey = netloc.split('.')[0]
    return sitekey

def dtMktClassivox(url, title, city, state):
    return mkSrcMktUri("url", "classivox", classivox_url_to_sitekey(url)])

### NAUGHTYREVIEWS

naughtyreviews_sitekey_to_marketid = {
                                      ("london",): "LHR",
                                      # springfield	ambiguous
                                      ("toronto",): "YYZ",
                                      ("detroit",): "DTW",
                                      ("atlanta",): "ATL",
                                      ("phoenix",): "PHX",
                                      ("dallas",): "DFW",
                                      # columbus	ambiguous
                                      ("portland",): "PDX",
                                      ("vancouver",): "YVR",
                                      ("miami",): "MIA",
                                      ("boston",): "BOS",
                                      # birmingham	ambiguous
                                      ("denver",): "DEN",
                                      # columbia	ambiguous
                                      ("houston",): "IAH",
                                      ("tampa",): "TPA",
                                      # manchester	ambiguous
                                      ("cleveland",): "CLE",
                                      # charleston	ambiguous
                                      # wilmington	ambiguous
                                      ("orlando",): "MCO",
                                      ("minneapolis",): "MSP",
                                      ("chicago",): "ORD",
                                      ("indianapolis",): "IND",
                                      # rochester	ambiguous
                                      ("pittsburgh",): "PIT",
                                      ("sacramento",): "SMF",
                                      ("cincinnati",): "CVG",
                                      ("paris",): "CDG",
                                      # lafayette	ambiguous
                                      ("nashville",): "BNA",
                                      ("baltimore",): "BWI",
                                      ("louisville",): "SDF",
                                      ("austin",): "AUS",
                                      # fayetteville	ambiguous
                                      ("cambridge",): "CBG",
                                      ("philadelphia",): "PHL",
                                      ("seattle",): "SEA",
                                      ("montreal",): "YUL",
                                      ("jackson",): "JAN",
                                      ("ottawa",): "YOW",
                                      ("charlotte",): "CLT",
                                      ("leicester",): "EMA",
                                      # bloomington	ambiguous
                                      ("southampton",): "SOU",
                                      ("milwaukee",): "MKE",
                                      ("jacksonville",): "JAX",
                                      ("calgary",): "YYC",
                                      ("tulsa",): "TUL",
                                      ("wichita",): "ICT",
                                      ("hamilton",): "YHM",
                                      ("eugene",): "EUG",
                                      ("albuquerque",): "ABQ",
                                      ("greensboro",): "GSO",
                                      ("amsterdam",): "AMS",
                                      ("memphis",): "MEM",
                                      ("leeds",): "LBA",
                                      ("albany",): "ALB",
                                      ("berlin",): "TXL",
                                      ("edmonton",): "YEG",
                                      ("bogota",): "BOG",
                                      ("raleigh",): "RDU",
                                      ("toledo",): "TOL",
                                      ("dusseldorf",): "DUS",
                                      ("kitchener",): "YKF",
                                      ("kiev",): "IEV",
                                      ("akron",): "CAK",
                                      ("asheville",): "AVL",
                                      ("fargo",): "FAR",
                                      ("biloxi",): "GPT",
                                      ("omaha",): "OMA",
                                      ("buffalo",): "BUF",
                                      ("brussels",): "BRU",
                                      ("medford",): "MFR",
                                      ("vienna",): "VIE",
                                      ("madison",): "MSN",
                                      ("milan",): "MXP",
                                      ("minot",): "MOT",
                                      ("dublin",): "DUB",
                                      ("greenville",): "GSP",
                                      ("lexington",): "LEX",
                                      ("sarasota",): "SRQ",
                                      ("madrid",): "MAD",
                                      ("bend",): "RDM",
                                      ("tokyo",): "NRT",
                                      ("hartford",): "HFD",
                                      ("reno",): "RNO",
                                      ("tallahassee",): "TLH",
                                      ("dayton",): "DAY",
                                      ("fredericksburg",): "EZF",
                                      ("caracas",): "CCS",
                                      ("knoxville",): "TYS",
                                      ("munich",): "MUC",
                                      ("bucharest",): "OTP",
                                      ("lisbon",): "LIS",
                                      ("warsaw",): "WAW",
                                      ("providence",): "PVD",
                                      ("brighton",): "ESH",
                                      ("lyon",): "LYS",
                                      ("savannah",): "SAV",
                                      ("chattanooga",): "CHA",
                                      ("tucson",): "TUS",
                                      ("barrie",): "QEB",
                                      ("halifax",): "YHZ",
                                      ("delhi",): "DEL",
                                      ("prague",): "PRG",
                                      ("shreveport",): "SHV",
                                      ("sydney",): "SYD",
                                      ("macon",): "MCN",
                                      ("brisbane",): "BNE",
                                      ("perth",): "PER",
                                      ("helsinki",): "HEL",
                                      ("zurich",): "ZRH",
                                      ("melbourne",): "MEL",
                                      ("amarillo",): "AMA",
                                      ("florence",): "FLO",
                                      ("pensacola",): "PNS",
                                      ("palmdale",): "PMD",
                                      ("missoula",): "MSO",
                                      ("sofia",): "SOF",
                                      ("stockholm",): "ARN",
                                      ("hampton",): "ORF",
                                      ("barcelona",): "BCN",
                                      ("moscow",): "SVO",
                                      ("naples",): "NAP",
                                      ("belfast",): "BFS",
                                      ("porto",): "OPO",
                                      ("richmond",): "RIC",
                                      ("dubai",): "DXB",
                                      ("newark",): "EWR",
                                      ("rome",): "FCO",
                                      ("worcester",): "ORH",
                                      ("frederick",): "FDK",
                                      ("newcastle",): "NCL",
                                      ("edinburgh",): "EDI",
                                      ("kolkata",): "CCU",
                                      ("bahia",): "SSA",
                                      ("hamburg",): "HAM",
                                      ("harrisburg",): "MDT",
                                      ("huntsville",): "HSV",
                                      ("burlington",): "BTV",
                                      ("istanbul",): "IST",
                                      ("nice",): "NCE",
                                      ("martinsburg",): "MRB",
                                      ("marseille",): "MRS",
                                      ("kelowna",): "YLW",
                                      ("gainesville",): "GNV",
                                      ("budapest",): "BUD",
                                      ("johannesburg",): "JNB",
                                      ("bristol",): "BRS",
                                      ("yuma",): "YUM",
                                      ("copenhagen",): "CPH",
                                      ("bangkok",): "BKK",
                                      ("quito",): "UIO",
                                      ("bellingham",): "BLI",
                                      ("shanghai",): "SHA",
                                      ("glasgow",): "GLA",
                                      ("lincoln",): "LNK",
                                      ("auckland",): "AKL",
                                      ("tijuana",): "TIJ",
                                      ("victoria",): "YYJ",
                                      ("arlington",): "IAD",
                                      ("oslo",): "OSL",
                                      ("youngstown",): "YNG",
                                      ("manila",): "MNL",
                                      ("windsor",): "YQG",
                                      ("roanoke",): "ROA",
                                      ("lima",): "LIM",
                                      ("flagstaff",): "FLG",
                                      ("santiago",): "SCL",
                                      ("chelmsford",): "STN",
                                      ("medellin",): "MDE",
                                      ("coventry",): "CVT",
                                      ("norfolk",): "ORF",
                                      ("rotterdam",): "RTM",
                                      ("chico",): "CIC",
                                      ("annapolis",): "ANP",
                                      ("honolulu",): "HNL",
                                      ("allentown",): "ABE",
                                      ("evansville",): "EVV",
                                      ("clarksville",): "CKV",
                                      ("morgantown",): "MGW",
                                      ("montgomery",): "MGM",
                                      ("winnipeg",): "YWG",
                                      ("frankfurt",): "FRA",
                                      ("joplin",): "JLN",
                                      ("bangalore",): "BLR",
                                      ("duluth",): "DLH",
                                      ("maracaibo",): "MAR",
                                      ("poughkeepsie",): "SWF",
                                      ("syracuse",): "SYR",
                                      ("beijing",): "PEK",
                                      ("modesto",): "MOD",
                                      ("cali",): "CLO",
                                      ("cancun",): "CUN",
                                      ("christchurch",): "CHC",
                                      ("sheffield",): "DSA",
                                      ("kingston",): "YGK",
                                      ("boise",): "BOI",
                                      ("mumbai",): "BOM",
                                      ("trenton",): "47N",
                                      ("kalamazoo",): "AZO",
                                      ("wellington",): "WLG",
                                      ("bismarck",): "BIS",
                                      ("concord",): "MHT",
                                      ("norwich",): "NWI",
                                      ("brazilia",): "BSB",
                                      ("liverpool",): "LPL",
                                      ("osaka",): "KIX",
                                      ("scranton",): "AVP",
                                      ("anchorage",): "ANC",
                                      ("singapore",): "SIN",
                                      ("hagerstown",): "HGR",
                                      ("topeka",): "FOE",
                                      ("oakland",): "OAK",
                                      ("strasbourg",): "SXB",
                                      ("davenport",): "MLI",
                                      ("cordoba",): "COR",
                                      ("saginaw",): "MBS",
                                      ("richland",): "PSC",
                                      ("bangor",): "PWM",
                                      ("guangzhou",): "CAN",
                                      ("mendoza",): "MDZ",
                                      ("bakersfield",): "BFL",
                                      ("waco",): "ACT",
                                      ("hyderabad",): "HYD",
                                      ("jakarta",): "CGK",
                                      ("moncton",): "YQM",
                                      ("asuncion",): "ASU",
                                      ("erie",): "ERI",
                                      ("fresno",): "FAT",
                                      ("augusta",): "AGS",
                                      ("spokane",): "GEG",
                                      ("lubbock",): "LBB",
                                      ("lansing",): "LAN",
                                      ("racine",): "RAC",
                                      ("bridgeport",): "BDR",
                                      ("seoul",): "ICN",
                                      ("butte",): "BTM",
                                      # fayettville	ambiguous
                                      ("tacoma",): "TCM",
                                      ("mobile",): "MOB",
                                      ("odessa",): "MAF",
                                      ("hattiesburg",): "HBG",
                                      ("casper",): "CPR",
                                      ("binghamton",): "BGM",
                                      ("champaign",): "CMI",
                                      ("billings",): "BIL",
                                      ("maui",): "OGG",
                                      ("boulder",): "WBU",
                                      ("flint",): "FNT",
                                      ("peoria",): "PIA",
                                      ("spartanburg",): "GSP",
                                      ("rockford",): "RFD",
                                      ("tuscaloosa",): "TCL",
                                      ("helena",): "HLN",
                                      ("stockton",): "SCK",
                                      ("kamloops",): "YKA",
                                      ("reading",): "RDG",
                                      ("monterey",): "MRY",
                                      ("stamford",): "HPN",
                                      ("regina",): "YQR",
                                      ("saskatoon",): "YXE",
                                      ("hammond",): "ORD",
                                      ("kokomo",): "OKK",
                                      ("bismark",): "BIS",
                                      ("frankurt",): "FRA",
                                      ("washington",): "IAD",
                                      ("charlottetown",): "YYG",
                                      ("hagatna",): "GUM",
                                      ("barre",): "BTV",
                                      ("roma",): "RMG",
                                      ("Leicester",): "EMA",
                                      ("nottingham",): "NQT",
                                      ("pittsburg",): "PIT",
                                      ("hollywood",): "BUR",
                                      ("santafe",): "SAF",
                                      # 2-WORD city names
                                      ("las", "vegas",): "LAS",
                                      ("los", "angeles",): "LAX",
                                      ("new", "york",): "JFK",
                                      ("san", "diego",): "SAN",
                                      ("palm", "beach",): "PBI",
                                      ("new", "orleans",): "MSY",
                                      ("st", "louis",): "STL",
                                      ("kansas", "city",): "MCI",
                                      ("washington", "dc",): "MWH",
                                      ("san", "jose",): "SJC",
                                      ("san", "francisco",): "SFO",
                                      ("panama", "city",): "PFN",
                                      ("orange", "county",): "SNA",
                                      ("san", "antonio",): "SAT",
                                      ("fort", "lauderdale",): "FLL",
                                      ("oklahoma", "city",): "OKC",
                                      ("central", "jersey",): "47N",
                                      ("grand", "rapids",): "GRR",
                                      ("myrtle", "beach",): "MYR",
                                      ("lake", "city",): "LCQ",
                                      ("des", "moines",): "DSM",
                                      ("daytona", "beach",): "DAB",
                                      ("baton", "rouge",): "BTR",
                                      ("south", "bend",): "SBN",
                                      ("green", "bay",): "GRB",
                                      ("kuala", "lumpur",): "KUL",
                                      ("fort", "myers",): "RSW",
                                      ("colorado", "springs",): "COS",
                                      ("long", "island",): "ISP",
                                      ("san", "juan",): "SJU",
                                      ("niagara", "falls",): "YCM",
                                      ("virginia", "beach",): "ORF",
                                      ("sioux", "falls",): "FSD",
                                      ("saint", "petersburg",): "LED",
                                      ("red", "deer",): "YQF",
                                      ("st", "cloud",): "STC",
                                      ("sao", "paulo",): "GRU",
                                      ("charlotte", "amalie",): "STT",
                                      ("little", "rock",): "LIT",
                                      ("ft", "mcmurray",): "YMM",
                                      ("new", "haven",): "HVN",
                                      ("buenos", "aires",): "EZE",
                                      ("mexico", "city",): "MEX",
                                      ("atlantic", "city",): "ACY",
                                      ("cape", "town",): "CPT",
                                      ("fort", "wayne",): "FWA",
                                      ("el", "paso",): "ELP",
                                      ("hilton", "head",): "HHH",
                                      ("inland", "empire",): "ONT",
                                      ("key", "west",): "EYW",
                                      ("lake", "charles",): "LCH",
                                      ("jersey", "city",): "EWR",
                                      ("hong", "kong",): "HKG",
                                      ("fort", "collins",): "FNL",
                                      ("santa", "barbara",): "SBA",
                                      ("corpus", "christi",): "CRP",
                                      ("la", "crosse",): "LSE",
                                      ("boca", "raton",): "FLL",
                                      ("northern", "virginia",): "IAD",
                                      ("rapid", "city",): "RAP",
                                      ("ann", "arbor",): "ARB",
                                      ("palm", "springs",): "PSP",
                                      ("taipei", "city",): "TPE",
                                      ("cedar", "rapids",): "CID",
                                      ("tel", "aviv",): "TLV",
                                      ("sioux", "city",): "SUX",
                                      ("great", "falls",): "GTF",
                                      ("long", "beach",): "LGB",
                                      ("terre", "haute",): "HUF",
                                      ("ventura", "county",): "OXR",
                                      ("fort", "smith",): "FSM",
                                      ("traverse", "city",): "TVC",
                                      ("st", "john",): "YQM",
                                      ("bowling", "green",): "BWG",
                                      ("santa", "fe",): "SAF",
                                      ("junction", "city",): "MHK",
                                      # 3-WORD city names
                                      ("san", "fernando", "valley",): "BUR",
                                      ("salt", "lake", "city",): "SLC",
                                      ("salvador", "de", "bahia",): "SSA",
                                      ("rio", "de", "janeiro",): "GIG",
                                      ("west", "palm", "beach",): "PBI",
                                      ("st", "john", "s",): "YYT",
                                      ("ho", "chi", "minh",): "SGN",
                                      ("san", "gabriel", "valley",): "EMT",
                                      ("rio", "grande", "valley",): "BRO"
                                      }

def process(url):
    bits = url.split('/')
    service = bits[3]
    if service in ["escorts", "companions"]:
        line = bits[-1]
        return processEscort(line)
    elif service in ["escort-agencies"]:
        line = bits[-1]
        return processAgency(line)
    elif service in ["na"]:
        print "N",
        line = bits[-1]
        return processEscort(line)
    elif service in ["massage-parlors"]:
        line = bits[-1]
        return processMassage(line)
    else:
        print "Didn't recognize service type %s" % service
        return 0

def lookupSitekey(terms):
    sk3 = naughtyreviews_sitekey_to_marketid.get(tuple(terms[-3:]))
    if sk3:
        return sk3
    sk2 = naughtyreviews_sitekey_to_marketid.get(tuple(terms[-2:]))
    if sk2:
        return sk2
    sk1 = naughtyreviews_sitekey_to_marketid.get(tuple(terms[-1:]))
    if sk1:
        return sk1
    return None

def isGenderMarker(t):
    return t in ["female", "woman", "male", "shemale", "tstvtg", "man", "couple", "female1"]

def isRaceEthnicMarker(t):
    return t in ["white", "black", "asian", "latin", "latino", "latina", "hispanic", "indian", "other", "european", "oriental", "russian", "mixed",""]

def isCompoundRaceEthnicMarker(t):
    return t in [["middle","eastern"]]

def trimNumericSuffix(terms):
    suffix = None
    try:
        i = int(terms[-1])
        suffix = terms[-1]
        terms.pop()
    except ValueError as e:
        pass
    return (suffix, terms)

def trimGenderMarker(terms):
    marker = None
    try:
        if isGenderMarker(terms[-1]):
            marker = terms[-1]
            terms.pop()
    except ValueError as e:
        pass
    return (marker, terms)
    
def trimRaceEthnicMarker(terms):
    marker = None
    try:
        if isCompoundRaceEthnicMarker(terms[-2:]):
            marker = "-".join(terms[-2:])
            terms.pop()
            terms.pop()
        elif isRaceEthnicMarker(terms[-1]):
            marker = terms[-1]
            terms.pop()
    except ValueError as e:
        pass
    return (marker, terms)

def processEscort(line):
    cands = 0
    try:
        terms = line.split('-')[1:]
        (suffix, terms) = trimNumericSuffix(terms)
        (gender, terms) = trimGenderMarker(terms)
        (raceEthnic, terms) = trimRaceEthnicMarker(terms)
        cands = lookupSitekey(terms[-3:])
    except Exception as e:
        print >> sys.stderr, "Give up on escort %r: [%s]" % (line, e)
        return 0
    return cands

def processAgency(line):
    cands = 0
    try:
        terms = line.split('-')[1:]
        (suffix, terms) = trimNumericSuffix(terms)
        cands = lookupSitekey(terms[-3:])
    except Exception as e:
        print >> sys.stderr, "Give up on agency %r: [%s]" % (line, e)
        return 0
    return cands

def processMassage(line):
    terms = line.split('-')[1:]
    return lookupSitekey(terms[-3:])

def naughtyreviews_url_to_marketid(url):
    """http://longisland.naughtyreviews.com/FemaleEscorts/s-mny-oo-chics-but-oo-nn-lik-oo-me-19/40317377"""
    try:
        return process(url)
    except Exception as e:
        print >> sys.stderr, e
        return None

def dtMktNaughtyreviews(url, title, city, state):
    # return mkSrcMktUri("url", "maughtreviews", "???")
    pass

### GENERIC

handlers_by_source = {
                      "backpage": dtMktBackpage,
                      "craigslist": dtMktCraigslist,
                      "classivox": dtMktClassivox,
                      "myproviderguide": dtMktMyproviderguide,
                      "naughtyreviews": dtMktNaughtyreviews,
                      "redbook": dtMktRedbook,
                      "cityvibe": dtMktCityvibe,
                      "massagetroll": dtMktMassagetroll,
                      "redbook_forum": dtMktRedbook_forum,
                      "cityxguide": dtMktCityxguide,
                      "cityxguideforum": dtMktCityxguideforum,
                      "rubads": dtMktRubads,
                      "anunico": dtMktAnunico,
                      "sipsap": dtMktSipsap,
                      "escortsincollege": dtMktEscortsincollege,
                      "escortphonelist": dtMktEscortphonelist,
                      "eroticmugshots": dtMktEroticmugshots,
                      "escortadsxxx": dtMktEscortadsxxx,
                      "escortsinca": dtMktEscortsinca,
                      "escortsintheus": dtMktEscortsintheus,
                      "liveescortreviews": dtMktLiveescortreviews,
                      "myproviderguideforum": dtMktMyproviderguideforum,
                      "usasexguide": dtMktUsasexguide,
                      "eroticreview": dtMktEroticreview,
                      "adultsearch": dtMktAdultsearch,
                      "happymassage": dtMktHappymassage,
                      "utopiaguide": dtMktUtopiaguide,
                      "missingkids": dtMktMissingkids,
                      "alibaba": dtMktAlibaba,
                      "justlanded": dtMktJustlanded,
                      "gmdu": dtMktGmdu,
                      "tradekey": dtMktTradekey,
                      "manpowervacancy": dtMktManpowervacancy,
                      "gulfjobsbank": dtMktGulfjobsbank,
                      "ec21": dtMktEc21}

def dtMkt(source, url, title, city, state, idx=None):
    try:
        source = int(source)
    except:
        pass
    try:
        handler = handlers_by_source[sources_by_id.get(source, source)]
        l = handler(url, title, city, state)
        if idx==None:
            return str(l)
        else:
            return l[idx]
    except Exception as e:
        print >> sys.stderr, e
    return None

print dtMkt('backpage',"""http://longisland.backpage.com/FemaleEscorts/s-mny-oo-chics-but-oo-nn-lik-oo-me-19/40317377""", "Hello", "Long Island", "New York")
